[project]
name = "mathe-core-mlib"
version = "2.1.1"
description = "Pacotes Úteis"
authors = [
    {name = "Matheus Lôbo",email = "matheusls@live.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama (>=0.4.6,<0.5.0)",
    "numpy (>=1.24.4,<3.0.0)",
    "scipy (>=1.10.1,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "pandas (>=2.0.3,<4.0.0)",
    "cycler (>=0.12.1,<0.13.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mkdocs (>=1.6.1,<2.0.0)",
    "mkdocs-material (>=9.7.5,<10.0.0)",
    "mkdocstrings[python] (>=1.0.3,<2.0.0)",
    "pydeps (>=3.0.2,<4.0.0)",
    "pre-commit (>=4.5.1,<5.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "ruff (>=0.15.17,<0.16.0)"
]

[[tool.poetry.packages]]
include = "mathe_core_mlib"
from = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff]
line-length = 140

# Versão mínima do Python que seus projetos suportam
target-version = "py312"

[tool.ruff.lint]
# Seleciona quais categorias de regras o Ruff vai verificar
select = [
    "E",  # pycodestyle errors (erros de estilo básicos)
    "W",  # pycodestyle warnings
    "F",  # pyflakes (erros de lógica, variáveis não usadas)
    "I",  # isort (organização de imports)
]

# Ignora algumas regras se elas forem muito chatas para o seu contexto (opcional)
ignore = []

[tool.ruff.format]
# Usa aspas duplas (padrão do Black)
quote-style = "double"
# Indentação com espaços
indent-style = "space"